# These are supported funding model platforms

github: [huanlin]
open_collective: # Replace with a single Open Collective username
ko_fi: michaeltsai
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://paypal.me/hltsai', 'https://leanpub.com/u/michaeltsai']
